In [5]:
import numpy as np 
arr = np.array([10,20,30,40,50])
print("Original Array: ",arr)
#after adding 2 to all elements 
print(" after addition: ", arr +2 )
#after multiplying by 3 
print(" after multiplication: ", 3*arr)
#after dividing every ele by 2 
print("after division: ", arr/2)

Original Array:  [10 20 30 40 50]
 after addition:  [12 22 32 42 52]
 after multiplication:  [ 30  60  90 120 150]
after division:  [ 5. 10. 15. 20. 25.]


In [7]:
import numpy as np
# part a)
arr = np.array([1, 2, 3, 6, 4, 5])

print("Original array:", arr)
print("Reversed array:", arr[::-1])

#part b) 
import numpy as np

# i
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

values, counts = np.unique(x, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(x == most_frequent)[0]

print("For x:")
print("Most frequent value:", most_frequent)
print("Indices:", indices)


# ii
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]
indices = np.where(y == most_frequent)[0]

print("\nFor y:")
print("Most frequent value:", most_frequent)
print("Indices:", indices)




Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]
For x:
Most frequent value: 1
Indices: [0 5 7 8 9]

For y:
Most frequent value: 1
Indices: [0 1 2]


In [8]:
import numpy as np

# Create 1-D array with 25 evenly spaced numbers from 10 to 100
Harshith = np.linspace(10, 100, 25)

print("Array:", Harshith)

# Dimensions of the array
print("Dimensions:", Harshith.ndim)

# Shape of the array
print("Shape:", Harshith.shape)

# Total number of elements
print("Total elements:", Harshith.size)

# Data type of each element
print("Data type:", Harshith.dtype)

# Total number of bytes consumed
print("Total bytes:", Harshith.nbytes)

# Transpose using reshape()
transpose_array = Harshith.reshape(25, 1)

print("Transpose using reshape():")
print(transpose_array)

# Transpose using T attribute
print("Transpose using T:")
print(Harshith.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [9]:
import numpy as np

# Create a 2-D array with 3 rows and 4 columns
ucs420_harshith = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Original Array:")
print(ucs420_harshith)

# Mean
print("Mean:", np.mean(ucs420_harshith))

# Median
print("Median:", np.median(ucs420_harshith))

# Maximum
print("Maximum:", np.max(ucs420_harshith))

# Minimum
print("Minimum:", np.min(ucs420_harshith))

# Unique elements
print("Unique elements:", np.unique(ucs420_harshith))

# Reshape to 4 rows and 3 columns
reshaped_ucs420_harshith = ucs420_harshith.reshape(4, 3)

print("Reshaped Array (4 x 3):")
print(reshaped_ucs420_harshith)

# Resize to 2 rows and 3 columns
resized_ucs420_harshith = np.resize(ucs420_harshith, (2, 3))

print("Resized Array (2 x 3):")
print(resized_ucs420_harshith)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
